[project]
name = "json-renderer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
]

[tool.black]
line-length=79


[project.scripts]
json-renderer = "main:main"
